### ISSUE TITLE
Will English version be provided?

### ISSUE THREAD

**Issue by KevinZonda** [BigCoke233/adams#6]

**Comment by KevinZonda** [comment]
I'm trying to translate -> https://github.com/KevinZonda/adams

**Comment by BigCoke233** [comment]
Hi, Kevin! Thanks for your issue.  
It has been a long time since the last update because I'm working on another theme called [Miracles](https://github.com/BigCoke233/miracles) and preparing for an important exam. So I have little time to develop Adams. Besides, I haven't completed the Multi-language function of Miracles. I'm glad to see someone working on the English edition of Adams, I would put your repo link in the REAME.md so that the users who speak English can see and use it.
Maybe, in the future, I would make a built-in English version.
And thanks again!

**Comment by KevinZonda** [comment]
SGTM, thanks a lot

**Comment by KevinZonda** [comment]
@BigCoke233 Hey, bro. I'm trapped in a problem. (I'm not a web developers, so my web skill is poor. QwQ)
I try to translate the `comment.php`, but seems that `date()` function didn't work fine.

https://github.com/KevinZonda/adams/blob/d0c594ca7b050937e268c81417a719bf219e371b/comment.php#L31

![image](https://user-images.githubusercontent.com/33132228/82751212-4becb900-9de8-11ea-8bcf-b765cdf2e317.png)

I also tried patch` var/Typecho/I18n.php` of typecho, but it still not work.

![image](https://user-images.githubusercontent.com/33132228/82751253-8b1b0a00-9de8-11ea-9839-1708dc603875.png)

**Comment by BigCoke233** [comment]
"18 小时前" means "18 hours ago", so maybe it's because the DateDiff setting is turned on. There should be a similar setting in Typecho but I'm not sure where it is and how to turn it off. 
But strange, this kind of time should be output by this function, `$this->dateWord();`.  And it works well in the theme Miracles.
Sorry that I can't help.
But it seems that it's a bug of Typecho. If the set language is English, it should output English text instead of Chinese. Typecho official has introduced the Multi-language function in this [document](https://github.com/lizheming/typecho-languages/tree/mo). If it's really a bug, you can create an issue to [Typecho](https://github.com/typecho/typecho).

**Comment by KevinZonda** [comment]
> "18 小时前" means "18 hours ago", so maybe it's because the DateDiff setting is turned on. There should be a similar setting in Typecho but I'm not sure where it is and how to turn it off.
> But strange, this kind of time should be output by this function, `$this->dateWord();`. And it works well in the theme Miracles.
> Sorry that I can't help.
> But it seems that it's a bug of Typecho. If the set language is English, it should output English text instead of Chinese. Typecho official has introduced the Multi-language function in this [document](https://github.com/lizheming/typecho-languages/tree/mo). If it's really a bug, you can create an issue to [Typecho](https://github.com/typecho/typecho).

Seems that does't work. I use stable branch, I will try dev branch later. Thanks a lot! :D
